import { useState } from 'react'
import {
  Container,
  Header,
  SpaceBetween,
  Button,
  Box,
  Alert,
  Textarea,
  FormField,
  Select,
  Cards,
  Badge,
  ExpandableSection
} from '@cloudscape-design/components'

interface QueryResult {
  id: string
  question: string
  answer: string
  confidence: number
  sourceDocument: string
  relevantSection: string
  timestamp: string
}

export default function QueryBenefitDoc() {
  const [loading, setLoading] = useState(false)
  const [query, setQuery] = useState('')
  const [selectedDocument, setSelectedDocument] = useState({ label: 'All Documents', value: 'all' })
  const [queryResults, setQueryResults] = useState<QueryResult[]>([
    {
      id: '1',
      question: 'What is the annual deductible for individual coverage?',
      answer: 'The annual deductible for individual coverage is $1,500 for in-network services and $3,500 for out-of-network services.',
      confidence: 95,
      sourceDocument: 'Health_Benefits_2024.pdf',
      relevantSection: 'Section 3: Deductibles and Cost Sharing',
      timestamp: '2024-12-10T15:30:00Z'
    },
    {
      id: '2',
      question: 'What preventive services are covered at 100%?',
      answer: 'Preventive services covered at 100% include annual physical exams, immunizations, mammograms, colonoscopies, and routine lab work when performed by in-network providers.',
      confidence: 88,
      sourceDocument: 'Health_Benefits_2024.pdf',
      relevantSection: 'Section 5: Preventive Care Benefits',
      timestamp: '2024-12-10T14:15:00Z'
    }
  ])

  const documentOptions = [
    { label: 'All Documents', value: 'all' },
    { label: 'Health_Benefits_2024.pdf', value: 'health_2024' },
    { label: 'Dental_Plan_Overview.pdf', value: 'dental_overview' },
    { label: 'PPO_Plan_Details.pdf', value: 'ppo_details' }
  ]

  const handleSubmitQuery = async () => {
    if (!query.trim()) return
    
    setLoading(true)
    
    // Simulate API call
    setTimeout(() => {
      const newResult: QueryResult = {
        id: Date.now().toString(),
        question: query,
        answer: 'This is a simulated response to your query. In a real implementation, this would be generated by analyzing the benefit documents using AI.',
        confidence: Math.floor(Math.random() * 30) + 70,
        sourceDocument: selectedDocument.value === 'all' ? 'Multiple Documents' : selectedDocument.label,
        relevantSection: 'Various sections analyzed',
        timestamp: new Date().toISOString()
      }
      
      setQueryResults([newResult, ...queryResults])
      setQuery('')
      setLoading(false)
    }, 2000)
  }

  const getConfidenceBadge = (confidence: number) => {
    if (confidence >= 90) return <Badge color="green">High Confidence ({confidence}%)</Badge>
    if (confidence >= 70) return <Badge color="blue">Medium Confidence ({confidence}%)</Badge>
    return <Badge color="red">Low Confidence ({confidence}%)</Badge>
  }

  return (
    <SpaceBetween size="l">
      <Header
        variant="h1"
        description="Ask questions about your benefit documents and get AI-powered answers"
      >
        Query Benefit Documents
      </Header>

      <Alert type="info">
        Use natural language to ask questions about your benefit documents. The AI will analyze the documents and provide relevant answers with confidence scores.
      </Alert>

      <Container>
        <SpaceBetween size="m">
          <Header variant="h2">Ask a Question</Header>
          
          <FormField label="Select Document Scope">
            <Select
              selectedOption={selectedDocument}
              onChange={({ detail }) => setSelectedDocument(detail.selectedOption as { label: string; value: string })}
              options={documentOptions}
              placeholder="Choose documents to query"
            />
          </FormField>

          <FormField
            label="Your Question"
            description="Ask about deductibles, coverage, premiums, exclusions, or any other benefit information"
          >
            <Textarea
              value={query}
              onChange={({ detail }) => setQuery(detail.value)}
              placeholder="e.g., What is my copay for specialist visits? What services require prior authorization?"
              rows={3}
            />
          </FormField>

          <Button
            variant="primary"
            onClick={handleSubmitQuery}
            loading={loading}
            disabled={!query.trim()}
          >
            Submit Query
          </Button>
        </SpaceBetween>
      </Container>

      <Container>
        <Cards
          cardDefinition={{
            header: (item: QueryResult) => (
              <SpaceBetween direction="vertical" size="xs">
                <Box variant="h3">Q: {item.question}</Box>
                <SpaceBetween direction="horizontal" size="xs">
                  {getConfidenceBadge(item.confidence)}
                  <Badge color="grey">{new Date(item.timestamp).toLocaleDateString()}</Badge>
                </SpaceBetween>
              </SpaceBetween>
            ),
            sections: [
              {
                id: 'answer',
                header: 'Answer',
                content: (item: QueryResult) => (
                  <Box variant="p">{item.answer}</Box>
                )
              },
              {
                id: 'source',
                header: 'Source Information',
                content: (item: QueryResult) => (
                  <ExpandableSection headerText="View Source Details" variant="footer">
                    <SpaceBetween size="s">
                      <Box>
                        <strong>Document:</strong> {item.sourceDocument}
                      </Box>
                      <Box>
                        <strong>Relevant Section:</strong> {item.relevantSection}
                      </Box>
                    </SpaceBetween>
                  </ExpandableSection>
                )
              }
            ]
          }}
          items={queryResults}
          loading={loading}
          loadingText="Processing your query..."
          empty={
            <Box textAlign="center" color="inherit">
              <b>No queries yet</b>
              <Box padding={{ bottom: 's' }} variant="p" color="inherit">
                Ask your first question about the benefit documents above.
              </Box>
            </Box>
          }
          header={<Header>Query Results</Header>}
        />
      </Container>
    </SpaceBetween>
  )
}